#!/usr/bin/env python3
"""Flag NWS marine-zone forecast periods where forecast SEAS are disproportionate to forecast
WIND -- i.e. distant-source swell, leftover sea, or an inbound system riding on top of a wind
field that could not have built that sea locally.

Motivating case: zone PKZ767 showed SW 15 kt with 10 ft seas mid-survey. A wind-only read would
have called that window benign; the seas are what actually governed launch operations.

THE HEURISTIC
-------------
Uses the Pierson-Moskowitz fully-developed-sea limit as a CEILING on how much significant wave
height local wind alone can build, in mariner units:

    Hs_ceiling[ft] ~= 0.021 x U[kt]^2        (PM: Hs = 0.0246 * U10^2 in SI)
    10 kt -> ~2 ft   15 kt -> ~5 ft   20 kt -> ~8.5 ft   25 kt -> ~13 ft   30 kt -> ~19 ft

PM is the theoretical MAXIMUM local wind can build given unlimited fetch and unlimited duration.
Fetch across the open Bering is effectively unlimited but duration rarely is, so a real local
wind-sea sits below this ceiling -- meaning forecast seas exceeding 1.5x the ceiling are
unambiguously NOT locally generated by the forecast wind alone. The conservatism runs the right
direction: every flag is real; some real swell events are missed only when the wind is also high,
and at high wind the wind figure is already its own warning. The heuristic's proper domain is
wind <= ~25 kt. The 50-80 m Bering shelf depth is NOT the operative constraint on wave growth at
these heights -- it slightly caps growth, which pushes real local seas further below the ceiling,
i.e. it makes the rule MORE conservative, not less.

Deliberately does NOT implement JONSWAP / SMB fetch-limited growth curves -- those need a fetch
length per wind direction that a zone forecast text cannot honestly supply; that would be false
precision dressed up in a one-line heuristic.

Flag rule: forecast_seas > --ratio (default 1.5) x ceiling  AND  forecast_seas >= --min-seas
(default 6 ft). Both are CLI flags on purpose -- --json logs the per-period ratio so the
threshold can be tuned against a few weeks of real zone text before being trusted operationally.

WIND CONVENTION: sustained wind only -- the MAX of all sustained "(\\d+) kt" mentions in the
period (handles "15 to 25 kt" ranges and "becoming" transitions). GUSTS ARE IGNORED ("Gusts to
N kt" / "gusts up to N kt"): waves answer to sustained wind, not an instantaneous gust.

SEAS CONVENTION: the MAX of all "ft" numbers found in any sentence that mentions "seas" (handles
"8 to 11 ft", "building to 15 ft", "5 ft or less", "combined seas N ft" -- no special-casing
needed since the extraction is number-after-"seas"-in-sentence, not a fixed phrase match).

INPUT
-----
Primary path: pipe zone-forecast text on stdin -- either a bare zone segment (starting
"PKZ767-...") or a full multi-zone Coastal Waters Forecast (CWF) product. Zones are split on
"^PKZ\\d{3}-" and each is labeled separately in the output.

Secondary path: --zone PKZ767 self-fetches the latest CWF from the NWS products API
(/products/types/CWF/locations/<--location, default ALU -- PKZ767 lives in the ALU product>) and
filters to that zone. Useful for testing against live text and as a fallback if the nws-forecast
MCP is down.

OUTPUT
------
One "SWELL:" line per flagged period (zone-labeled, stable prefix, greppable), plus one standing
caveat line per run. The only numbers printed are the forecast's own plus the computed ratio --
never a predicted seas figure. The implied cause is always a disjunction (swell / leftover sea /
system inbound), never a single named cause. If the forecast text itself already says "swell",
the line is still printed with "(forecast names the swell itself)" appended -- confirmation, not
discovery. Unparsed periods (wording this parser doesn't recognize) are counted and reported
rather than silently dropped.

Usage:
    cat zone.txt | python3 scripts/swell-flag.py
    <nws-forecast MCP marine text> | python3 scripts/swell-flag.py --json
    python3 scripts/swell-flag.py --zone PKZ767
    python3 scripts/swell-flag.py --zone PKZ767 --ratio 1.75 --min-seas 5
"""
import argparse
import json
import re
import sys
import urllib.request

UA = "swell-flag/1.0 (NOAA Ship Fairweather /daily; accounts@dmanda.com)"
API = "https://api.weather.gov"

ZONE_HEADER_RE = re.compile(r"^(PKZ\d{3})-", re.M)
ZONE_NAME_RE = re.compile(r"^([A-Za-z][A-Za-z0-9 ,.'&/()+-]*?)-\s*$")
PERIOD_RE = re.compile(r"^\.([A-Z][A-Z0-9 ,+/-]*?)\.\.\.", re.M)
GUST_RE = re.compile(r"gusts?\s+(?:up\s+to|to|as\s+high\s+as|near)\s+\d+\s*kt", re.I)
WIND_KT_RE = re.compile(r"(\d+)\s*kt", re.I)
DIR_RE = re.compile(
    r"\b(NNE|NNW|NE|NW|ENE|ESE|E|SE|SSE|S|SSW|SW|WSW|W|WNW|N|VARIABLE)\s+WIND\b", re.I
)
SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+")


# ------------------------------------------------------------ heuristic math
def pm_ceiling_ft(wind_kt):
    """Pierson-Moskowitz fully-developed-sea Hs, in feet, for sustained wind in knots."""
    return 0.021 * wind_kt ** 2


# ------------------------------------------------------------ parsing
def split_zones(text):
    """-> list of {'id', 'name', 'text'}. Falls back to a single 'UNSPECIFIED' zone if no
    PKZ header line is present (e.g. period text pasted without the UGC header)."""
    matches = list(ZONE_HEADER_RE.finditer(text))
    if not matches:
        return [{"id": "UNSPECIFIED", "name": None, "text": text}]
    zones = []
    for i, m in enumerate(matches):
        start = m.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        seg = text[start:end]
        name = None
        lines = seg.splitlines()
        if len(lines) > 1:
            nm = ZONE_NAME_RE.match(lines[1].strip())
            if nm:
                name = nm.group(1)
        zones.append({"id": m.group(1), "name": name, "text": seg})
    return zones


def extract_periods(zone_text):
    """-> list of (raw_period_name, body_text). Skips SYNOPSIS blocks (narrative, not a
    discrete wind/seas period) so they don't inflate the unparsed count."""
    matches = list(PERIOD_RE.finditer(zone_text))
    out = []
    for i, m in enumerate(matches):
        name = m.group(1).strip()
        if name.upper().startswith("SYNOPSIS"):
            continue
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(zone_text)
        body = zone_text[start:end].split("$$")[0]
        out.append((name, body))
    return out


def extract_wind_kt(body):
    """MAX sustained kt value in the period. Gusts are masked out before extraction."""
    masked = GUST_RE.sub(" ", body)
    vals = [int(v) for v in WIND_KT_RE.findall(masked)]
    return max(vals) if vals else None


def extract_seas_ft(body):
    """MAX ft value found in any sentence mentioning 'seas' (case-insensitive). Extracting
    every digit after the word 'seas' within its sentence -- rather than matching a fixed
    phrase -- is what makes 'to' ranges, 'building to', 'or less', and 'combined seas' all
    work without separate cases."""
    flat = " ".join(body.split())
    vals = []
    for sentence in SENTENCE_SPLIT_RE.split(flat):
        idx = sentence.lower().find("seas")
        if idx == -1:
            continue
        tail = sentence[idx:]
        tail_lower = tail.lower()
        if "ft" not in tail_lower and "foot" not in tail_lower:
            continue
        vals.extend(int(n) for n in re.findall(r"\d+", tail))
    return max(vals) if vals else None


def extract_direction(body):
    m = DIR_RE.search(body)
    if not m:
        return None
    d = m.group(1).upper()
    return "Variable" if d == "VARIABLE" else d


def nice_period(name):
    return " ".join(w.capitalize() for w in name.split())


# ------------------------------------------------------------ self-fetch
def fetch_latest_cwf(location, timeout):
    """Latest CWF product text for a NWS product-location code (e.g. ALU). ~15 lines by design
    -- this is a test/fallback path, not the primary input (stdin from the nws-forecast MCP is)."""
    req = urllib.request.Request(
        f"{API}/products/types/CWF/locations/{location}",
        headers={"User-Agent": UA, "Accept": "application/ld+json"},
    )
    with urllib.request.urlopen(req, timeout=timeout) as r:
        lst = json.loads(r.read())
    graph = lst.get("@graph") or []
    if not graph:
        raise RuntimeError(f"no CWF products listed for location {location}")
    graph.sort(key=lambda p: p.get("issuanceTime") or "", reverse=True)
    req2 = urllib.request.Request(
        graph[0]["@id"], headers={"User-Agent": UA, "Accept": "application/ld+json"}
    )
    with urllib.request.urlopen(req2, timeout=timeout) as r:
        prod = json.loads(r.read())
    return prod.get("productText", "") or ""


# ------------------------------------------------------------ output
CAVEAT = "_heuristic wind-vs-seas ratio check — flags disproportion; it is not a sea-state forecast_"


def swell_line(zone_id, period_name, direction, wind, seas, ceiling, ratio, names_swell):
    dir_str = f"{direction} " if direction else ""
    line = (
        f"SWELL: {zone_id} {nice_period(period_name)} — {dir_str}{wind} kt but seas {seas} ft "
        f"(~{ratio:.1f}x the ~{ceiling:.1f} ft that {wind} kt can build): not locally wind-driven "
        f"— distant swell, leftover sea, or a system inbound. Look closer at period/direction "
        f"before calling the window workable."
    )
    if names_swell:
        line += " (forecast names the swell itself)"
    return line


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--zone", help="self-fetch the latest NWS CWF and filter to this zone (e.g. PKZ767); omit to read stdin")
    ap.add_argument("--location", default="ALU", help="NWS CWF product location for --zone self-fetch (default ALU; PKZ767 lives here)")
    ap.add_argument("--ratio", type=float, default=1.5, help="flag when seas > ratio x PM ceiling (default 1.5)")
    ap.add_argument("--min-seas", type=float, default=6.0, help="flag only when seas >= this many ft (default 6)")
    ap.add_argument("--timeout", type=float, default=20.0, help="self-fetch network timeout, seconds (default 20)")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    def emit(periods, unparsed, note=None):
        if args.json:
            out = {
                "ratio_threshold": args.ratio,
                "min_seas_ft": args.min_seas,
                "periods": periods,
                "unparsed_periods": unparsed,
            }
            if note:
                out["note"] = note
            print(json.dumps(out, indent=2))
        else:
            if note:
                print(f"SWELL: {note}")
                return
            flagged = [p for p in periods if p["flagged"]]
            if flagged:
                for p in flagged:
                    print(swell_line(p["zone"], p["period"], p["direction"], p["wind_kt_max"],
                                      p["seas_ft_max"], p["ceiling_ft"], p["ratio"], p["names_swell"]))
            else:
                print("(no disproportionate periods this run)")
            print(CAVEAT)
            print(f"note: {unparsed} periods unparsed")

    # --- gather input text ------------------------------------------------
    if args.zone:
        try:
            text = fetch_latest_cwf(args.location, args.timeout)
        except Exception as e:
            emit([], 0, note=f"self-fetch failed for --zone {args.zone} ({type(e).__name__}: {e})")
            return
    else:
        try:
            text = sys.stdin.read()
        except Exception as e:
            emit([], 0, note=f"could not read stdin ({type(e).__name__}: {e})")
            return

    if not text or not text.strip():
        emit([], 0, note="no input text (empty stdin) — nothing to check")
        return

    zones = split_zones(text)
    if args.zone:
        wanted = args.zone.upper()
        zones = [z for z in zones if z["id"] == wanted]
        if not zones:
            emit([], 0, note=f"zone {args.zone} not found in fetched {args.location} product — nothing to check")
            return

    # --- extract periods across all zones ----------------------------------
    all_blocks = []
    for z in zones:
        for name, body in extract_periods(z["text"]):
            all_blocks.append((z["id"], name, body))

    if not all_blocks:
        emit([], 0, note="no parseable forecast periods found in input — nothing to check")
        return

    periods = []
    unparsed = 0
    for zone_id, name, body in all_blocks:
        wind = extract_wind_kt(body)
        seas = extract_seas_ft(body)
        if wind is None or seas is None:
            unparsed += 1
            continue
        ceiling = pm_ceiling_ft(wind)
        ratio = (seas / ceiling) if ceiling > 0 else (float("inf") if seas > 0 else 0.0)
        flagged = bool(seas > args.ratio * ceiling and seas >= args.min_seas)
        periods.append({
            "zone": zone_id,
            "period": name,
            "direction": extract_direction(body),
            "wind_kt_max": wind,
            "seas_ft_max": seas,
            "ceiling_ft": round(ceiling, 2),
            "ratio": round(ratio, 2) if ratio != float("inf") else None,
            "flagged": flagged,
            "names_swell": bool(re.search(r"swell", body, re.I)),
        })

    emit(periods, unparsed)


if __name__ == "__main__":
    main()
